# ABOUTME: Tests that the Windows install.bat script has valid syntax and correct path references
# ABOUTME: Regression coverage for issues #349 (line-break), #407 (binary not found), #356 (path errors)

"""Regression tests for the Windows install.bat script embedded in package.py.

The install.bat is generated by the package command and executed on user machines.
Bugs in this script are catastrophic — users can't install at all. These tests
validate static properties that can be checked without actually running the .bat:

1. No unmatched quotes or parentheses (causes syntax errors)
2. All %USERPROFILE% references are properly quoted for spaces in paths
3. Critical file copy targets are correct
4. Error handling (errorlevel checks) present after each copy

Bugs prevented:
- #349: Line-break handling broke install.bat on some Windows locales
- #407: Binary path resolution failed (credential-process.exe not found)
- #356: binary_name variable unset caused silent install failure
"""

import re
from pathlib import Path

import pytest

# The install.bat is embedded as a string in package.py. Extract it for testing.
PACKAGE_PY = Path(__file__).resolve().parents[1] / "governed_inference_platform" / "cli" / "commands" / "package.py"


def _extract_install_bat() -> str:
    """Extract the main install.bat content from package.py source."""
    content = PACKAGE_PY.read_text(encoding="utf-8")

    # The main installer starts with '@echo off' followed by 'SETLOCAL ENABLEDELAYEDEXPANSION'
    # to distinguish it from other small @echo off snippets (websearch headers, launcher).
    lines = content.splitlines()
    bat_lines = []
    in_bat = False
    for i, line in enumerate(lines):
        if not in_bat and "@echo off" in line:
            # Check if next line has SETLOCAL — that's the main installer
            if i + 1 < len(lines) and "SETLOCAL" in lines[i + 1]:
                in_bat = True
                idx = line.find("@echo off")
                bat_lines.append(line[idx:])
                continue
        if in_bat:
            # The batch script ends when we hit a line that's clearly Python
            # (triple-quote end, or dedented Python code)
            stripped = line.strip()
            if stripped in ('"""', "'''") or (stripped.startswith("installer_path") and "=" in stripped):
                break
            # Remove Python string indentation (typically 4-8 spaces of indent)
            bat_lines.append(line)

    assert bat_lines, "Could not extract install.bat from package.py"
    return "\n".join(bat_lines)


class TestInstallBatSyntax:
    """Validate install.bat has correct batch script syntax."""

    @pytest.fixture
    def bat_content(self):
        return _extract_install_bat()

    def test_starts_with_echo_off(self, bat_content):
        """Batch script must start with @echo off."""
        assert bat_content.strip().startswith("@echo off"), "install.bat must begin with @echo off"

    def test_no_unmatched_parentheses_in_if_blocks(self, bat_content):
        """Every opening ( in an if/else block must have a matching )."""
        open_count = bat_content.count("(")
        close_count = bat_content.count(")")
        # Allow small imbalance from REM comments, but flag large mismatches
        assert abs(open_count - close_count) <= 2, (
            f"Parenthesis mismatch: {open_count} open vs {close_count} close — likely a broken if/else block"
        )

    def test_userprofile_paths_use_quotes(self, bat_content):
        """Paths with %USERPROFILE% must be quoted (handles spaces in username).
        Pattern: any line with %USERPROFILE% that isn't in a REM comment
        should have the path wrapped in quotes."""
        lines = bat_content.splitlines()
        violations = []
        for i, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped.startswith("REM") or stripped.startswith("::"):
                continue
            if "%USERPROFILE%" in line:
                # Check if the USERPROFILE reference is inside quotes
                # or is the argument to mkdir/if exist (which don't need quotes)
                if "mkdir" in line or "if exist" in line or "if not exist" in line:
                    continue
                # For copy/del/move commands, the path should be quoted
                if any(cmd in line.lower() for cmd in ["copy", "del", "move", "xcopy"]):
                    # Find the %USERPROFILE% reference and check for surrounding quotes
                    if '"%USERPROFILE%' not in line and '"%~dp0' not in line:
                        violations.append(f"Line {i}: {stripped}")
        assert not violations, "Unquoted %USERPROFILE% paths (spaces in username will break):\n" + "\n".join(
            f"  • {v}" for v in violations
        )

    def test_copies_credential_process(self, bat_content):
        """install.bat must copy credential-process-windows.exe."""
        assert "credential-process-windows.exe" in bat_content, "install.bat must copy the credential process binary"

    def test_copies_config_json(self, bat_content):
        """install.bat must copy config.json to the install directory."""
        assert "config.json" in bat_content, "install.bat must copy config.json"

    def test_has_error_handling_after_copy(self, bat_content):
        """Installed files use the transaction helper rather than blind copies."""
        lines = bat_content.splitlines()
        copy_indices = [i for i, l in enumerate(lines) if "copy /Y" in l.lower() or "copy /y" in l]
        assert not copy_indices
        assert "-InstallAll" in PACKAGE_PY.read_text(encoding="utf-8")

    def test_no_hardcoded_drive_letters(self, bat_content):
        """User-data paths must not use hardcoded C:\\ — use %USERPROFILE% or %~dp0.
        System paths like C:\\Program Files are acceptable (standard locations)."""
        lines = bat_content.splitlines()
        violations = []
        # Well-known system paths that are legitimately hardcoded
        allowed_patterns = ["Program Files", "ProgramData", "Windows\\System32"]
        for i, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped.startswith("REM") or stripped.startswith("::"):
                continue
            # Match C:\ or D:\ etc but not inside echo/comment strings
            if re.search(r"[A-Z]:\\(?!Users\\%)", line) and "echo" not in line.lower():
                # Allow well-known system paths
                if any(p in line for p in allowed_patterns):
                    continue
                violations.append(f"Line {i}: {stripped}")
        assert not violations, "Hardcoded drive letters found (won't work on D:\\ installs):\n" + "\n".join(
            f"  • {v}" for v in violations[:5]
        )

    def test_no_unix_line_endings_assumption(self, bat_content):
        """The script must not rely on \\n-only line endings.
        Batch scripts on Windows must use \\r\\n. Check that there's no
        explicit \\n manipulation that would break on Windows."""
        # This is a static check — the actual line endings depend on git config
        # but the script content shouldn't have explicit \n string manipulation
        assert "\\n" not in bat_content or "echo." in bat_content, (
            "install.bat should not contain literal \\n escape sequences"
        )

    def test_headless_installer_never_pauses(self, bat_content):
        assert not any(line.strip().lower() == "pause" for line in bat_content.splitlines())

    def test_successful_installer_explicitly_exits_zero(self, bat_content):
        source = PACKAGE_PY.read_text(encoding="utf-8")
        assert source.count("exit /b 0") >= 2

    def test_source_package_files_are_never_rewritten(self, bat_content):
        assert "Set-Content 'cowork-3p.reg'" not in bat_content
        assert "Set-Content 'gip-settings" not in bat_content
        assert "Set-Content 'harnesses" not in bat_content

    def test_powershell_harness_enumeration_parenthesizes_command(self):
        source = PACKAGE_PY.read_text(encoding="utf-8")
        assert "foreach ($harnessFile in (Get-ChildItem -LiteralPath $harnessRoot -File -Recurse))" in source
        assert "$harnessFile.FullName.Substring" in source
